#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#define F_CPU 16000000L
#define PRESCALER 8
#define MAX_16_BIT_INT 65535

#define HEADER_SEGMENTS_SIZE 15
#define DATA_SEGMENTS_SIZE 40

#define MICROSECONDS_IN_SECOND_F 1000000.0
#define MICROSECOND_MULT_RATIO (PRESCALER * MICROSECONDS_IN_SECOND_F) / F_CPU

#define BLUE_LED PINC0
#define RED_LED PINC3

#endif /* CONSTANTS_H_ */